name: Continous Integration

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master

env:
  CI: 1

jobs:
  diff:
    name: Show user-service CDK-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: npm ci

      - run: npm run cdk diff LambdaStack --ci --no-color 2>&1 | tee cdk.diff
